name: app
description: AtLogin mobile application
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0-0.0 <3.0.0"

dependencies:
  at_client_mobile: 1.0.0+10
  at_demo_data: ^0.0.3+1
  at_server_status: ^0.1.0+1
  at_commons: ^1.0.1+5
  path_provider: ^2.0.1
  flutter_qr_reader: ^1.0.3
  pedantic: ^1.11.0
  flutter:
    sdk: flutter
  image_picker: ^0.7.4
  font_awesome_flutter: ^8.8.1
  auto_size_text: ^2.1.0
  image_cropper: ^1.2.2
  material_design_icons_flutter: ^4.0.5345
  permission_handler: ^6.1.3
  url_launcher: ^6.0.3
  provider: ^5.0.0
  flutter_local_notifications: ^5.0.0+1
  receive_sharing_intent: ^1.4.2
  uni_links: ^0.2.0
  webview_flutter: ^2.0.4
  image: ^3.0.2
  at_onboarding_flutter: ^1.0.0+4
  at_backupkey_flutter: ^1.0.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  # integration_test:
    # sdk: flutter

dependency_overrides:
  crypto: 3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/atsign.png
    - assets/logo.png
