name: desktop_app
description: Desktop AtLogin Test App

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  at_lookup: ^1.0.0+5
  provider: ^5.0.0
  barcode_widget: ^2.0.1
  charcode: ^1.2.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
