name: server
description: A web server built using the shelf package.
# version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: '>=2.12.0-0.0 <3.0.0'

dependencies:
  args: ^2.0.0
  at_client: ^1.0.1+9
  at_commons: ^1.0.1+7
  at_lookup: ^1.0.0+7
  at_server_status: ^0.1.0+2
  barcode_image: ^2.0.0
  charcode: ^1.2.0
  image: ^3.0.2
  shelf: ^1.1.4
  shelf_cookie: ^1.1.1
  shelf_router: ^1.0.0
  shelf_static: ^1.0.0

dev_dependencies:
  pedantic: ^1.10.0

dependency_overrides:
  args: ^2.0.0 # overridden for barcode_image
  convert: ^3.0.0 # overidden for shelf_static
  shelf: ^1.0.0 # overriden for  shelf_router
  image: ^3.0.1
  crypto: 3.0.0
