name: server
description: A web server built using the shelf package.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0-0.0 <3.0.0'

dependencies:
  args: ^2.0.0
  shelf: ^1.0.0
  shelf_router: ^0.7.4
  shelf_static: ^1.0.0
  shelf_cookie: ^1.1.1
  at_client: ^1.0.1+7
  at_commons: ^1.0.1+5
  barcode_image: ^2.0.0-nullsafety
  image: ^3.0.1
  charcode: ^1.2.0

dev_dependencies:
  pedantic: ^1.10.0

dependency_overrides:
  args: ^2.0.0 # overridden for barcode_image
  convert: ^3.0.0 # overidden for shelf_static
  shelf: ^1.0.0 # overriden for  shelf_router
  image: ^3.0.1
  crypto: 3.0.0

